server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com # localhost
  client:
    register-with-eureka: false
    fetch-registry: false #不需要检索服务
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/